language: c
install:
- sudo apt-get install graphviz
script: ./configure --prefix="$PWD/root" && make
after_success: if [[ -n ${TRAVIS_TAG} ]]; then make zip dist_name=${TRAVIS_TAG}; fi
deploy:
  provider: releases
  api_key:
    secure: NYwuSqqRF8zr9gCgG18/El30RUZC3noTEb23mEicqpFZZw8zqWDQ+QpzyfwH6xWzFR7a8hIhpnSVqz8AIL5jLJPHigjTudEQsT3rugZFEJlsJ13jJIYGZMbMgBD02rfy67gBXMPjrf2mZGDdpwrhZtzpOJy7MLL8+a7eVXELSgI=
  file: tmp/${TRAVIS_TAG}.zip
  on:
    repo: webb/git-graphviz
    all_branches: true
    tags: true
